<script setup lang="ts">
import { computed, nextTick, ref } from "vue";
import { ChevronDown, ClipboardCheck, Download, FileArchive, FileCode, FileSpreadsheet, FileText, FlaskConical, KeyRound, Plus, Search, Trash2, Upload } from "@lucide/vue";
import { saveBlob, teacherApi } from "./teacher.api";
import { initialQuestionScore, validateQuestionScores } from "./teacher.scoring";
import { useTeacherStore } from "./teacher.store";
import type { Course, LearningTask, Question, QuestionType, Resource, Submission } from "./teacher.types";
import TeacherModal from "./TeacherModal.vue";

type WorkspaceTab = "COURSE" | "HOMEWORK" | "EXPERIMENT" | "MATERIAL";
type TaskDialog = "CREATE" | "INFO" | "QUESTIONS" | "SUBMISSIONS" | null;
const store = useTeacherStore();
const semester = ref("ALL"); const courseSearch = ref(""); const selectedCourseId = ref<number | null>(null); const tab = ref<WorkspaceTab>("COURSE"); const resourceSearch = ref("");
const uploadInput = ref<HTMLInputElement | null>(null); const uploadKind = ref<Resource["kind"]>("MATERIAL"); const uploading = ref(false);
const selectedTaskId = ref<number | null>(null); const taskDialog = ref<TaskDialog>(null); const submissionTab = ref<"SUBMITTED" | "UNSUBMITTED">("SUBMITTED"); const submissionPage = ref(1); const selectedSubmissionId = ref<number | null>(null);
const message = ref(""); const busy = ref(false); const expandedTypes = ref<Set<QuestionType>>(new Set(["SINGLE"])); const questionScores = ref<Record<number, number>>({});
const taskForm = ref({ taskType: "HOMEWORK" as LearningTask["taskType"], name: "", description: "", startAt: "2099-01-01T08:00", deadline: "2099-12-31T23:59", maxScore: 100 });
const questions = ref<Question[]>([]); const teacherScore = ref(0); const teacherComment = ref("");
const inviteCode = ref("");

const courses = computed(() => (store.workspace?.courses || []).filter((course) => (semester.value === "ALL" || course.semester === semester.value) && (!courseSearch.value || `${course.name}${course.className}${course.code}`.toLowerCase().includes(courseSearch.value.toLowerCase()))));
const selectedCourse = computed(() => store.workspace?.courses.find((course) => course.id === selectedCourseId.value) || null);
const selectedTask = computed(() => selectedCourse.value?.tasks.find((task) => task.id === selectedTaskId.value) || null);
const selectedSubmission = computed(() => selectedTask.value?.submissions.find((item) => item.id === selectedSubmissionId.value) || null);
const courseResources = computed(() => (selectedCourse.value?.resources || []).filter((item) => ["COURSE", "QUESTION_BANK"].includes(item.kind) && (!resourceSearch.value || item.name.toLowerCase().includes(resourceSearch.value.toLowerCase()))));
const materials = computed(() => (selectedCourse.value?.resources || []).filter((item) => item.kind === "MATERIAL"));
const taskRows = computed(() => (selectedCourse.value?.tasks || []).filter((item) => item.taskType === (tab.value === "HOMEWORK" ? "HOMEWORK" : "EXPERIMENT")));
const submissionRows = computed(() => (selectedTask.value?.submissions || []).filter((item) => submissionTab.value === "SUBMITTED" ? item.submitted : !item.submitted));
const pagedSubmissions = computed(() => submissionRows.value.slice((submissionPage.value - 1) * 10, submissionPage.value * 10));
const submissionPageCount = computed(() => Math.max(1, Math.ceil(submissionRows.value.length / 10)));
const questionGroups = computed(() => (["SINGLE", "MULTIPLE", "TRUE_FALSE", "FILL", "SHORT"] as QuestionType[]).map((type) => ({ type, label: questionTypeLabel(type), items: questions.value.filter((item) => item.type === type) })));

function deadZone(event: MouseEvent, callback: () => void) { const element = event.currentTarget as HTMLElement; const rect = element.getBoundingClientRect(); const ratio = (event.clientX - rect.left) / rect.width; if (ratio > .1 && ratio < .9) callback(); }
function openCourse(course: Course) { selectedCourseId.value = course.id; tab.value = "COURSE"; resourceSearch.value = ""; }
function closeCourse() { selectedCourseId.value = null; taskDialog.value = null; selectedSubmissionId.value = null; }
function fmt(value: string) { return new Date(value).toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }); }
function localDate(value: string) { const date = new Date(value); const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return local.toISOString().slice(0, 16); }
function iconFor(item: Resource) { if (item.name.endsWith(".xlsx") || item.name.endsWith(".csv")) return FileSpreadsheet; if (item.name.endsWith(".sql") || item.name.endsWith(".json")) return FileCode; if (item.name.endsWith(".zip")) return FileArchive; return FileText; }
function chooseUpload(kind: Resource["kind"]) { uploadKind.value = kind; uploadInput.value?.click(); }
async function upload(event: Event) { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file || !selectedCourse.value) return; uploading.value = true; message.value = ""; try { await teacherApi.uploadResource(selectedCourse.value.id, uploadKind.value, false, file); await store.reload(); message.value = `${file.name} 上传成功`; } catch (e) { message.value = (e as Error).message; } finally { uploading.value = false; input.value = ""; } }
async function download(item: Resource) { const result = await teacherApi.downloadResource(item.id); saveBlob(result.blob, result.filename); }
async function downloadTemplate() { const result = await teacherApi.downloadQuestionTemplate(); saveBlob(result.blob, result.filename); }
async function removeResource(item: Resource) { message.value = ""; try { await teacherApi.deleteResource(item.id); await store.reload(); } catch (e) { message.value = (e as Error).message; } }
async function createInviteCode() { if (!selectedCourse.value) return; const result = await teacherApi.regenerateInviteCode(selectedCourse.value.id); inviteCode.value = result.code || ""; message.value = result.code ? `课程邀请码：${result.code}（30 天内有效）` : "邀请码生成失败"; }

function openCreate(type: LearningTask["taskType"]) { selectedTaskId.value = null; taskForm.value = { taskType: type, name: "", description: "", startAt: "2099-01-01T08:00", deadline: "2099-12-31T23:59", maxScore: 100 }; taskDialog.value = "CREATE"; message.value = ""; }
function openInfo(task: LearningTask) { selectedTaskId.value = task.id; taskForm.value = { taskType: task.taskType, name: task.name, description: task.description, startAt: localDate(task.startAt), deadline: localDate(task.deadline), maxScore: task.maxScore }; taskDialog.value = "INFO"; message.value = ""; }
async function saveTask() { if (!selectedCourse.value) return; busy.value = true; message.value = ""; const payload = { ...taskForm.value, startAt: new Date(taskForm.value.startAt).toISOString(), deadline: new Date(taskForm.value.deadline).toISOString() }; try { if (taskDialog.value === "CREATE") await teacherApi.createTask(selectedCourse.value.id, payload); else if (selectedTask.value) await teacherApi.updateTask(selectedTask.value.id, payload); await store.reload(); taskDialog.value = null; } catch (e) { message.value = (e as Error).message; } finally { busy.value = false; } }
function openQuestions(task: LearningTask) { selectedTaskId.value = task.id; questions.value = structuredClone(task.questions || []); taskDialog.value = "QUESTIONS"; message.value = ""; }
function addQuestion(type: QuestionType) { questions.value.push({ id: Math.max(0, ...questions.value.map((item) => item.id)) + 1, type, title: "", options: type === "SINGLE" || type === "MULTIPLE" ? ["选项 A", "选项 B"] : [], answer: "", score: type === "SHORT" ? 20 : 10 }); expandedTypes.value.add(type); }
function removeQuestion(id: number) { questions.value = questions.value.filter((item) => item.id !== id); }
function toggleType(type: QuestionType) { const next = new Set(expandedTypes.value); next.has(type) ? next.delete(type) : next.add(type); expandedTypes.value = next; }
async function saveQuestions() { if (!selectedTask.value) return; if (questions.value.some((item) => !item.title.trim() || item.score < 0)) { message.value = "请填写完整题目并检查分值"; return; } busy.value = true; try { await teacherApi.updateQuestions(selectedTask.value.id, questions.value); await store.reload(); taskDialog.value = null; } catch (e) { message.value = (e as Error).message; } finally { busy.value = false; } }
function optionsText(item: Question) { return item.options.join("\n"); }
function setOptions(item: Question, value: string) { item.options = value.split("\n").map((part) => part.trim()).filter(Boolean); }
function questionTypeLabel(type: QuestionType) { return { SINGLE: "单选题", MULTIPLE: "多选题", TRUE_FALSE: "判断题", FILL: "填空题", SHORT: "简答题" }[type]; }

function openSubmissions(task: LearningTask) { selectedTaskId.value = task.id; submissionTab.value = "SUBMITTED"; submissionPage.value = 1; taskDialog.value = "SUBMISSIONS"; selectedSubmissionId.value = null; }
function answerFor(questionId: number) { return selectedSubmission.value?.answers.find((item) => item.questionId === questionId)?.answer || "未作答"; }
function openSubmission(item: Submission) { if (!item.submitted || !selectedTask.value) return; selectedSubmissionId.value = item.id; teacherScore.value = item.teacherScore ?? item.aiScore ?? 0; teacherComment.value = item.teacherComment || ""; questionScores.value = {}; if (selectedTask.value.taskType === "HOMEWORK") { for (const question of selectedTask.value.questions) questionScores.value[question.id] = initialQuestionScore(question, answerForFrom(item, question.id), item.aiScore || 0, selectedTask.value.maxScore); teacherScore.value = Object.values(questionScores.value).reduce((sum, score) => sum + score, 0); } }
function answerForFrom(item: Submission, questionId: number) { return item.answers.find((answer) => answer.questionId === questionId)?.answer || ""; }
function validQuestionScores() { return Boolean(selectedTask.value && validateQuestionScores(selectedTask.value.questions, questionScores.value)); }
function scoreChanged() { teacherScore.value = Object.values(questionScores.value).reduce((sum, score) => sum + Number(score || 0), 0); }
async function saveGrade() { if (!selectedSubmission.value || !selectedTask.value) return; if (selectedTask.value.taskType === "HOMEWORK" && !validQuestionScores()) { message.value = "单选、判断、填空只能填写 0 分或满分；其他题型须填写分值范围内的整数"; return; } if (!Number.isInteger(Number(teacherScore.value)) || teacherScore.value < 0 || teacherScore.value > selectedTask.value.maxScore) { message.value = `总分必须是 0 到 ${selectedTask.value.maxScore} 的整数`; return; } busy.value = true; message.value = ""; try { await teacherApi.grade(selectedSubmission.value.id, { teacherScore: Number(teacherScore.value), teacherComment: teacherComment.value }); await store.reload(); selectedSubmissionId.value = null; message.value = "批改结果已保存"; } catch (e) { message.value = (e as Error).message; } finally { busy.value = false; } }
</script>

<template>
  <section class="page"><div class="page-head"><div><h1>课程管理</h1><p>查看本人授课课程，并进入课程工作区处理教学任务。</p></div></div>
    <div class="toolbar"><div class="filter-group"><label>学期</label><select v-model="semester"><option value="ALL">全部</option><option v-for="item in store.workspace?.semesters" :key="item" :value="item">{{ item }}</option></select></div><div class="search-box"><Search :size="17" /><input v-model="courseSearch" placeholder="搜索课程、班级或课程编号" /></div></div>
    <div class="course-grid"><article v-for="course in courses" :key="course.id" class="course-card dead-zone" tabindex="0" @dblclick="deadZone($event, () => openCourse(course))" @keydown.enter="openCourse(course)"><div class="course-code"><span>{{ course.code }}</span><span class="tag">{{ new Date(course.tasks[0]?.deadline || 0) >= new Date() ? '进行中' : '已归档' }}</span></div><h2>{{ course.name }}</h2><p>{{ course.className }}<br />{{ course.semester }}</p><div class="course-foot"><span>{{ course.studentCount }} 名学生</span><span>{{ course.tasks.length }} 项任务</span></div></article><div v-if="!courses.length" class="empty-state">没有符合条件的授课课程</div></div>
  </section>

  <input ref="uploadInput" class="vue-hidden-input" type="file" @change="upload" />
  <TeacherModal v-if="selectedCourse" :title="selectedCourse.name" :subtitle="`${selectedCourse.className} · ${selectedCourse.semester}`" size="large" @close="closeCourse">
    <nav class="tabs"><button :class="{ active: tab === 'COURSE' }" @click="tab = 'COURSE'">课程</button><button :class="{ active: tab === 'HOMEWORK' }" @click="tab = 'HOMEWORK'">作业</button><button :class="{ active: tab === 'EXPERIMENT' }" @click="tab = 'EXPERIMENT'">实验</button><button :class="{ active: tab === 'MATERIAL' }" @click="tab = 'MATERIAL'">资料</button></nav>
    <div class="modal-body grow"><p v-if="message" :class="message.includes('成功') || message.includes('保存') ? 'notice-bar' : 'toast-inline'">{{ message }}</p>
      <section v-if="tab === 'COURSE'" class="tab-view active"><div class="toolbar"><div class="search-box"><Search :size="16" /><input v-model="resourceSearch" placeholder="搜索课程资源" /></div><button class="btn" @click="createInviteCode"><KeyRound :size="16" />{{ inviteCode ? `邀请码 ${inviteCode}` : '生成邀请码' }}</button><button class="btn" @click="chooseUpload('COURSE')"><Upload :size="16" />上传资源</button></div><div class="resource-list"><div v-for="item in courseResources" :key="item.id" class="resource-row" :class="{ 'question-bank': item.kind === 'QUESTION_BANK' }"><i class="file-icon"><component :is="iconFor(item)" :size="18" /></i><div class="resource-main"><strong>{{ item.name }}</strong><span>{{ item.sourceLabel }} · {{ fmt(item.createdAt) }}</span></div><div class="resource-actions"><button v-if="item.kind === 'QUESTION_BANK'" @click="downloadTemplate">模板下载</button><button v-if="item.kind === 'QUESTION_BANK'" @click="chooseUpload('QUESTION_BANK')">新增题库</button><button @click="download(item)">下载</button></div></div><div v-if="!courseResources.length" class="empty-state">暂无课程资源</div></div></section>
      <section v-else-if="tab === 'HOMEWORK' || tab === 'EXPERIMENT'" class="tab-view active"><div class="list-toolbar"><div><h3>{{ tab === 'HOMEWORK' ? '线上作业' : '课程实验' }}</h3><p>{{ tab === 'HOMEWORK' ? '布置题目、调整发布时间并批改学生答案。' : '发布实验说明并复核实验报告。' }}</p></div><button class="btn primary" @click="openCreate(tab === 'HOMEWORK' ? 'HOMEWORK' : 'EXPERIMENT')"><Plus :size="16" />新增{{ tab === 'HOMEWORK' ? '作业' : '实验' }}</button></div><div class="assignment-list"><article v-for="task in taskRows" :key="task.id" class="assignment-row dead-zone" @dblclick="deadZone($event, () => openSubmissions(task))"><i class="file-icon"><ClipboardCheck v-if="task.taskType === 'HOMEWORK'" :size="18" /><FlaskConical v-else :size="18" /></i><div class="resource-main"><strong>{{ task.name }}</strong><span>{{ fmt(task.startAt) }} 至 {{ fmt(task.deadline) }} · 提交 {{ task.submittedCount }}/{{ task.studentCount }} · 已批 {{ task.gradedCount }}</span></div><div class="task-actions"><button class="btn" @click.stop="openSubmissions(task)">批改{{ task.taskType === 'HOMEWORK' ? '作业' : '实验' }}</button><button v-if="task.taskType === 'HOMEWORK'" class="btn" @click.stop="openQuestions(task)">修改作业</button><button class="btn" @click.stop="openInfo(task)">修改信息</button></div></article><div v-if="!taskRows.length" class="empty-state">暂无{{ tab === 'HOMEWORK' ? '作业' : '实验' }}</div></div></section>
      <section v-else class="tab-view active"><div class="list-toolbar"><div><h3>课程资料</h3><p>上传实验模板、参考文件和课程附件。</p></div><button class="btn primary" @click="chooseUpload('MATERIAL')"><Upload :size="16" />上传资料</button></div><div class="resource-list"><div v-for="item in materials" :key="item.id" class="resource-row"><i class="file-icon"><component :is="iconFor(item)" :size="18" /></i><div class="resource-main"><strong>{{ item.name }}</strong><span>{{ fmt(item.createdAt) }}</span></div><div class="resource-actions"><button @click="download(item)"><Download :size="15" />下载</button><button v-if="item.ownedByCurrentTeacher" class="danger" @click="removeResource(item)"><Trash2 :size="15" />删除</button></div></div><div v-if="!materials.length" class="empty-state">暂无资料</div></div></section>
    </div>
  </TeacherModal>

  <TeacherModal v-if="taskDialog === 'CREATE' || taskDialog === 'INFO'" :title="taskDialog === 'CREATE' ? `新增${taskForm.taskType === 'HOMEWORK' ? '作业' : '实验'}` : '修改任务信息'" :subtitle="taskDialog === 'CREATE' ? '默认时间设置在 2099 年，不会立即发布' : selectedTask?.name" size="small" @close="taskDialog = null"><div class="modal-body"><div class="form-grid"><label class="field-label full">名称<input v-model="taskForm.name" :placeholder="taskForm.taskType === 'HOMEWORK' ? '留空时按当前时间生成作业名称' : '实验名称'" /></label><label class="field-label">开始时间<input v-model="taskForm.startAt" type="datetime-local" /></label><label class="field-label">截止时间<input v-model="taskForm.deadline" type="datetime-local" /></label><label class="field-label">满分<input v-model.number="taskForm.maxScore" type="number" min="1" /></label><label class="field-label full">{{ taskForm.taskType === 'HOMEWORK' ? '作业说明' : '实验要求' }}<textarea v-model="taskForm.description" /></label></div><p v-if="message" class="toast-inline">{{ message }}</p></div><footer class="modal-footer"><button class="btn" @click="taskDialog = null">取消</button><button class="btn primary" :disabled="busy" @click="saveTask">{{ busy ? '保存中' : taskDialog === 'CREATE' ? '创建' : '保存' }}</button></footer></TeacherModal>

  <TeacherModal v-if="taskDialog === 'QUESTIONS' && selectedTask" title="编辑作业题目" :subtitle="selectedTask.name" size="large" @close="taskDialog = null"><div class="modal-body grow"><div class="question-editor"><section v-for="group in questionGroups" :key="group.type" class="question-block"><header><button class="section-toggle" @click="toggleType(group.type)"><strong>{{ group.label }}</strong><span>{{ group.items.length }} 题</span><ChevronDown :size="17" /></button><button class="btn" @click="addQuestion(group.type)"><Plus :size="15" />新增</button></header><div v-if="expandedTypes.has(group.type)" class="vue-stack"><article v-for="(item, index) in group.items" :key="item.id" class="editor-row"><div class="question-fields"><label class="field-label full">题目文本<textarea v-model="item.title" /></label><label v-if="item.type === 'SINGLE' || item.type === 'MULTIPLE'" class="field-label full">选项（每行一个）<textarea :value="optionsText(item)" @input="setOptions(item, ($event.target as HTMLTextAreaElement).value)" /></label><label v-if="item.type !== 'SHORT'" class="field-label">答案<input v-model="item.answer" /></label><label class="field-label">分值<input v-model.number="item.score" type="number" min="0" /></label></div><button class="btn danger" @click="removeQuestion(item.id)"><Trash2 :size="15" />删除第 {{ index + 1 }} 题</button></article></div></section></div><p v-if="message" class="toast-inline">{{ message }}</p></div><footer class="modal-footer"><span>当前总分：{{ questions.reduce((sum, item) => sum + Number(item.score || 0), 0) }}</span><button class="btn" @click="taskDialog = null">取消</button><button class="btn primary" :disabled="busy" @click="saveQuestions">保存题目</button></footer></TeacherModal>

  <TeacherModal v-if="taskDialog === 'SUBMISSIONS' && selectedTask" :title="`批改${selectedTask.taskType === 'HOMEWORK' ? '作业' : '实验'}`" :subtitle="selectedTask.name" size="nested" @close="taskDialog = null"><nav class="tabs"><button :class="{ active: submissionTab === 'SUBMITTED' }" @click="submissionTab = 'SUBMITTED'; submissionPage = 1">已提交 {{ selectedTask.submittedCount }}</button><button :class="{ active: submissionTab === 'UNSUBMITTED' }" @click="submissionTab = 'UNSUBMITTED'; submissionPage = 1">未提交 {{ selectedTask.studentCount - selectedTask.submittedCount }}</button></nav><div class="modal-body grow"><p v-if="message" class="notice-bar">{{ message }}</p><div class="student-list"><article v-for="item in pagedSubmissions" :key="item.id" class="student-row dead-zone" tabindex="0" @dblclick="deadZone($event, () => openSubmission(item))" @keydown.enter="openSubmission(item)"><div><strong>{{ item.studentName }}</strong><span>{{ item.studentNo }}<template v-if="item.submittedAt"> · {{ fmt(item.submittedAt) }}</template></span></div><span v-if="item.submitted" class="score">AI 初评 {{ item.aiScore ?? '--' }} 分</span><span v-else class="state-pill">未提交</span></article><div v-if="!pagedSubmissions.length" class="empty-state">当前名单为空</div></div><div class="pager"><button :disabled="submissionPage <= 1" @click="submissionPage--">上一页</button><span>第 {{ submissionPage }} / {{ submissionPageCount }} 页</span><button :disabled="submissionPage >= submissionPageCount" @click="submissionPage++">下一页</button></div></div></TeacherModal>

  <TeacherModal v-if="selectedSubmission && selectedTask" :title="`${selectedSubmission.studentName} · ${selectedTask.taskType === 'HOMEWORK' ? '逐题批改' : '实验报告批改'}`" :subtitle="`${selectedSubmission.studentNo} · AI 初评 ${selectedSubmission.aiScore ?? '--'} 分`" size="large" @close="selectedSubmissionId = null"><div class="submission-layout"><section class="submission-preview"><template v-if="selectedTask.taskType === 'HOMEWORK'"><h3>学生作业</h3><article v-for="(question, index) in selectedTask.questions" :key="question.id" class="answer-block"><strong>{{ index + 1 }}. {{ question.title }}（{{ question.score }} 分）</strong><p>学生答案：{{ answerFor(question.id) }}</p><small>参考答案：{{ question.answer || '教师人工评阅' }}</small></article></template><template v-else><h3>学生实验报告</h3><div class="report-preview">{{ selectedSubmission.reportText || '未读取到实验报告正文。' }}</div></template></section><aside class="grading-side"><template v-if="selectedTask.taskType === 'HOMEWORK'"><h3>逐题评分</h3><div v-for="question in selectedTask.questions" :key="question.id" class="score-row"><div><strong>{{ questionTypeLabel(question.type) }}</strong><span>满分 {{ question.score }}</span></div><input v-model.number="questionScores[question.id]" type="number" min="0" :max="question.score" step="1" @input="scoreChanged" /></div></template><template v-else><h3>AI 评价</h3><div class="ai-review">{{ selectedSubmission.aiReview }}</div></template><label class="field-label">教师评分<input v-model.number="teacherScore" type="number" min="0" :max="selectedTask.maxScore" :readonly="selectedTask.taskType === 'HOMEWORK'" /></label><label class="field-label">教师评价<textarea v-model="teacherComment" placeholder="可选填写" /></label><p v-if="message" class="toast-inline">{{ message }}</p><button class="btn primary" :disabled="busy" @click="saveGrade">保存批改结果</button></aside></div></TeacherModal>
</template>
