package cloud.zhixuyun.admin;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import jakarta.annotation.PostConstruct;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Map;

@Repository
public class BackupArchiveRepository {
    private final JdbcTemplate backupJdbc;

    public BackupArchiveRepository(@Qualifier("backupJdbcTemplate") JdbcTemplate backupJdbc) {
        this.backupJdbc = backupJdbc;
    }

    @PostConstruct
    void init() {
        backupJdbc.execute("""
                create table if not exists archived_student_backup (
                  id bigint generated by default as identity primary key,
                  original_user_id bigint not null,
                  login_name varchar(120) not null,
                  display_name varchar(120) not null,
                  email varchar(120),
                  student_no varchar(40),
                  grade_year varchar(20),
                  administrative_class_name varchar(120),
                  snapshot_json clob not null,
                  archived_at timestamp with time zone not null,
                  purge_after timestamp with time zone not null
                )
                """);
    }

    public void saveArchivedStudent(Map<String, Object> snapshot, Instant archivedAt, Instant purgeAfter) {
        backupJdbc.update("""
                insert into archived_student_backup(
                  original_user_id,login_name,display_name,email,student_no,grade_year,administrative_class_name,snapshot_json,archived_at,purge_after
                ) values (?,?,?,?,?,?,?,?,?,?)
                """,
                snapshot.get("id"), snapshot.get("loginName"), snapshot.get("displayName"), snapshot.get("email"),
                snapshot.get("studentNo"), snapshot.get("gradeYear"), snapshot.get("administrativeClassName"),
                String.valueOf(snapshot.get("snapshotJson")), Timestamp.from(archivedAt), Timestamp.from(purgeAfter));
    }

    public int purgeExpired(Instant now) {
        return backupJdbc.update("delete from archived_student_backup where purge_after <= ?", Timestamp.from(now));
    }

    public List<Map<String, Object>> latestBackups() {
        return backupJdbc.query("""
                select original_user_id, login_name, display_name, archived_at, purge_after
                from archived_student_backup
                order by archived_at desc
                """, (rs, row) -> Map.of(
                "originalUserId", rs.getLong("original_user_id"),
                "loginName", rs.getString("login_name"),
                "displayName", rs.getString("display_name"),
                "archivedAt", rs.getTimestamp("archived_at").toInstant(),
                "purgeAfter", rs.getTimestamp("purge_after").toInstant()
        ));
    }
}
