create table if not exists user_account (
  id bigint generated by default as identity primary key,
  login_name varchar(120) not null unique,
  password_hash varchar(100) not null,
  display_name varchar(80) not null,
  role varchar(20) not null,
  enabled boolean not null default true,
  email varchar(120),
  phone varchar(40),
  bio varchar(200),
  must_change_password boolean not null default false,
  failed_login_attempts int not null default 0,
  avatar_content_type varchar(120),
  avatar_content bytea
);

alter table user_account add column if not exists email varchar(120);
alter table user_account add column if not exists phone varchar(40);
alter table user_account add column if not exists bio varchar(200);
alter table user_account add column if not exists must_change_password boolean not null default false;
alter table user_account add column if not exists failed_login_attempts int not null default 0;
alter table user_account add column if not exists avatar_content_type varchar(120);
alter table user_account add column if not exists avatar_content bytea;

create table if not exists auth_session (
  token varchar(100) primary key,
  user_id bigint not null references user_account(id) on delete cascade,
  expires_at timestamp with time zone not null
);

create table if not exists teacher_profile (
  user_id bigint primary key references user_account(id) on delete cascade,
  department varchar(100) not null,
  title varchar(60) not null,
  email varchar(120),
  phone varchar(40),
  bio varchar(1000)
);

create table if not exists administrative_class (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  grade_year varchar(20) not null,
  major_name varchar(120),
  enabled boolean not null default true
);

create table if not exists student_profile (
  user_id bigint primary key references user_account(id) on delete cascade,
  student_no varchar(40) not null unique,
  grade_year varchar(20),
  administrative_class_id bigint references administrative_class(id) on delete set null
);

create table if not exists course (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references user_account(id) on delete cascade,
  name varchar(120) not null,
  code varchar(40) not null,
  class_name varchar(120) not null,
  semester varchar(80) not null,
  schedule_text varchar(200),
  student_count int not null default 0,
  color varchar(20) not null default '#07876e'
);

create table if not exists teaching_class (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course(id) on delete cascade,
  name varchar(120) not null,
  term varchar(80) not null,
  enabled boolean not null default true
);

create table if not exists course_teacher_assignment (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course(id) on delete cascade,
  teacher_id bigint not null references user_account(id) on delete cascade,
  role_code varchar(30) not null default 'INSTRUCTOR',
  subject_or_duty varchar(160)
);

create table if not exists teaching_class_teacher_assignment (
  id bigint generated by default as identity primary key,
  teaching_class_id bigint not null references teaching_class(id) on delete cascade,
  teacher_id bigint not null references user_account(id) on delete cascade,
  role_code varchar(30) not null default 'INSTRUCTOR',
  subject_or_duty varchar(160)
);

create table if not exists platform_setting (
  setting_key varchar(80) primary key,
  setting_value varchar(500)
);

create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  actor_id bigint references user_account(id) on delete set null,
  action varchar(80) not null,
  target_type varchar(80),
  target_id varchar(80),
  detail varchar(500),
  created_at timestamp with time zone not null
);

create table if not exists course_resource (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course(id) on delete cascade,
  owner_id bigint references user_account(id) on delete set null,
  kind varchar(30) not null,
  name varchar(255) not null,
  source_label varchar(120) not null,
  shared boolean not null default false,
  content_type varchar(120),
  storage_backend varchar(40),
  storage_key varchar(500),
  file_size bigint,
  content bytea,
  created_at timestamp with time zone not null
);

alter table course_resource add column if not exists storage_backend varchar(40);
alter table course_resource add column if not exists storage_key varchar(500);
alter table course_resource add column if not exists file_size bigint;

create table if not exists learning_task (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course(id) on delete cascade,
  task_type varchar(20) not null,
  name varchar(180) not null,
  description text,
  start_at timestamp with time zone not null,
  deadline timestamp with time zone not null,
  max_score int not null default 100,
  questions_json text,
  created_at timestamp with time zone not null
);

create table if not exists task_submission (
  id bigint generated by default as identity primary key,
  task_id bigint not null references learning_task(id) on delete cascade,
  student_name varchar(80) not null,
  student_no varchar(40) not null,
  submitted boolean not null default false,
  submitted_at timestamp with time zone,
  ai_score int,
  teacher_score int,
  answers_json text,
  report_text text,
  ai_review text,
  teacher_comment text,
  review_status varchar(20) not null default 'SUBMITTED',
  current_version_no int not null default 0
);

alter table task_submission add column if not exists review_status varchar(20) not null default 'SUBMITTED';
alter table task_submission add column if not exists current_version_no int not null default 0;

create table if not exists submission_version (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references task_submission(id) on delete cascade,
  version_no int not null,
  report_text text,
  attachment_json text,
  ai_score int,
  ai_review text,
  created_at timestamp with time zone not null,
  unique(submission_id, version_no)
);

create table if not exists course_enrollment (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course(id) on delete cascade,
  student_id bigint not null references user_account(id) on delete cascade,
  active boolean not null default true,
  joined_at timestamp with time zone not null,
  unique(course_id, student_id)
);

create table if not exists course_invite_code (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course(id) on delete cascade,
  invite_code varchar(20) not null unique,
  enabled boolean not null default true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone not null
);

create table if not exists user_notification (
  id bigint generated by default as identity primary key,
  user_id bigint not null references user_account(id) on delete cascade,
  notification_type varchar(30) not null,
  title varchar(220) not null,
  content varchar(1000) not null,
  source_type varchar(40),
  source_id bigint,
  is_read boolean not null default false,
  created_at timestamp with time zone not null
);

create table if not exists rubric_template (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references user_account(id) on delete cascade,
  name varchar(160) not null,
  dimensions_json text not null,
  enabled boolean not null default true,
  version_no int not null default 1,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);

create table if not exists teaching_alert (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references user_account(id) on delete cascade,
  title varchar(240) not null,
  summary varchar(500) not null,
  target_name varchar(160) not null,
  level varchar(20) not null,
  status varchar(20) not null,
  analysis text not null,
  evidence text,
  proposal text,
  created_at timestamp with time zone not null
);

create table if not exists assistant_session (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references user_account(id) on delete cascade,
  title varchar(200) not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);

create table if not exists assistant_message (
  id bigint generated by default as identity primary key,
  session_id bigint not null references assistant_session(id) on delete cascade,
  role varchar(20) not null,
  content text not null,
  created_at timestamp with time zone not null
);

create table if not exists conversation (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references user_account(id) on delete cascade,
  student_id bigint references user_account(id) on delete set null,
  contact_name varchar(120) not null,
  contact_type varchar(20) not null,
  avatar_text varchar(10),
  unread_count int not null default 0,
  updated_at timestamp with time zone not null
);

alter table conversation add column if not exists student_id bigint references user_account(id) on delete set null;

create table if not exists conversation_message (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references conversation(id) on delete cascade,
  sender varchar(20) not null,
  title varchar(220),
  content text not null,
  created_at timestamp with time zone not null
);

create index if not exists idx_course_teacher on course(teacher_id);
create index if not exists idx_student_profile_class on student_profile(administrative_class_id);
create index if not exists idx_teaching_class_course on teaching_class(course_id);
create index if not exists idx_course_teacher_assignment_course on course_teacher_assignment(course_id);
create index if not exists idx_audit_log_time on audit_log(created_at desc);
create index if not exists idx_task_course on learning_task(course_id);
create index if not exists idx_submission_task on task_submission(task_id);
create index if not exists idx_submission_version on submission_version(submission_id, version_no desc);
create index if not exists idx_course_enrollment_student on course_enrollment(student_id, active);
create index if not exists idx_notification_user_time on user_notification(user_id, created_at desc);
create index if not exists idx_rubric_teacher on rubric_template(teacher_id, updated_at desc);
create index if not exists idx_alert_teacher_time on teaching_alert(teacher_id, created_at desc);
create index if not exists idx_session_teacher_time on assistant_session(teacher_id, updated_at desc);
create index if not exists idx_conversation_teacher_time on conversation(teacher_id, updated_at desc);
create index if not exists idx_conversation_student on conversation(teacher_id, student_id);
